services:
  - type: web
    name: portfolio-backend
    plan: free
    runtime: docker
    dockerfilePath: ./portfolio/Dockerfile
    envVars:
      - key: FRONTEND_URL
        value: https://geetbhute.vercel.app
